name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'main-test'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '11'
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4.1.0
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.1.0
      - name: Build with Gradle
        run: ./gradlew build --no-configuration-cache --no-daemon --stacktrace --continue
      - name: Publish build reports
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-reports
          path: "**/build/reports"

