name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'main-test'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: temurin
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.0
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: build --no-configuration-cache --no-daemon --stacktrace --continue
      - name: Publish build reports
        if: always()
        uses: actions/upload-artifact@v4.3.1
        with:
          name: build-reports
          path: build/reports

